### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by frankystone** [comment]
What about using GPLv3?

We need to adapt README.md i think.

**Comment by gunchleoc** [comment]
I don't know about changing licenses without contacting everyone who has contributed to the repo. That might be a legal requirement.

**Comment by frankystone** [comment]
I currently don't find the motivation to work on any parts of the widelands project, sorry. Feel free to remove me as an admin/chieftain from this project on this platform.

Anyway i will stay lurking around...

**Comment by gunchleoc** [comment]
I'm really sorry to hear that, I very much enjoy working with you. Glad you'll keep lurking :)

**Pull request merged**
