### PR TITLE
restrict time a user can edit his own post

### PR DESCRIPTION
**Pull request by frankystone**
The time a user is allowed to edit his own post is is set to 24 hours. This can be changed in settings.py with the new option EDIT_HOURS.

I did also some small refactoring, maybe we should test this on alpha.

My first pull request on github...

### CODE REVIEW

**Review by stonerl — APPROVED** [review]
LGTM 👍

**Comment by frankystone** [comment]
Thanks :-)

Made a last test locally... can you apply the changes onto the server? I will write a forum post then to publish this change.

**Comment by stonerl** [comment]
I have it on my list. I’m away till next week. I’ll let you know when it is deployed.

**Comment by frankystone** [comment]
Thanks :-)

**Comment by gunchleoc** [comment]
Great to see you back :)

**Comment by stonerl** [comment]
deployed

**Comment by frankystone** [comment]
Thanks!

**Pull request merged**
