### PR TITLE
Forum read button

### LINKED ISSUE #198: Feature request for forum: Mark all as read
I'd like to see a functionality within one forum to mark all topics in this forum as read, to get rid of the "Unread posts" icon in that forum.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-05-30T13:02:11Z
 * owner: qcumber-some
 * the launchpad url was https://bugs.launchpad.net/bugs/587509

### PR DESCRIPTION
**Pull request by frankystone**
Fixes #198 

Adds a button "Mark all as read" to the forums view. The button is only shown for logged in users.

### CODE REVIEW

**Comment by frankystone** [comment]
Because i don't pay attention to those unread signs in the forum and thus i am unfamiliar with the use cases:

@Noordfrees : Where do you need such a button? Currently it is only in a forum view, e.g. https://www.widelands.org/forum/forum/1/ Do you want it also in a forum cathegory view, e.g. https://www.widelands.org/forum/category/1/ and/or in the forums overview, https://www.widelands.org/forum/ ?

**Comment by blotter** [comment]
ich bin für alle drei :)

**Comment by frankystone** [comment]
Nicht optimal, braucht wohl etwas css, oder?

mark_read_forum

**Review by blotter — APPROVED** [review]
lief ohne fehler auf alpha

**Pull request merged**
